---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 1984
    targetPort: 1984
  - name: rtsp
    protocol: TCP
    port: 8554
    targetPort: 8554