app:
  name: go2rtc

cert:
  dnsName: "*.home.justinricheson.com"

ingress:
  dnsName: cams.home.justinricheson.com

deployment:
  image:
    repository: alexxit/go2rtc
    tag: "latest"

config:
  cams:
    doorbell:
      ip: 10.20.0.10

secret:
  # Generate with: htpasswd -nbB admin "$ADMIN_PASSWORD"
  hashedUsers: "put the result in secrets.yaml"
  cams:
    doorbell:
      pw: "put the result in secrets.yaml"