---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  # Disable traefik auth middleware for now
  # HA makes it difficult to disable native auth
  # annotations:
  #   traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Values.app.name }}-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress.dnsName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "home-assistant"
            port:
              number: 8080
  tls:
  - hosts:
    - {{ .Values.ingress.dnsName }}
    secretName: wildcard-tls