app:
  name: technitium-dns

cert:
  dnsName: "*.home.justinricheson.com"

ingress:
  dnsName: dns.home.justinricheson.com

service:
  ip: 10.10.0.11

deployment:
  image:
    repository: technitium/dns-server
    tag: "latest"

volumes:
  size: 1Gi