app:
  name: frigate-ui

cert:
  dnsName: "*.home.justinricheson.com"

ingress:
  dnsName: nvr.home.justinricheson.com

secret:
  # Generate with: htpasswd -nbB admin "$ADMIN_PASSWORD"
  hashedUsers: "put the result in secrets.yaml"